/**
 * TypeScript API type definitions for OntoSight visualization engine.
 *
 * These types mirror the Pydantic models defined in the Python backend.
 * Generated to match ontosight/models.py and ontosight/server/models/api.py
 *
 * Contract Alignment:
 * - Node<T> ↔ Pydantic Node[T]
 * - Edge<T> ↔ Pydantic Edge[T]
 * - HyperEdge<T> ↔ Pydantic HyperEdge[T]
 *
 * All types support JSON serialization and are used for API request/response
 * validation.
 *
 * Archived Types (Phase 7+ features):
 * - TreeNode<T> - Backend support planned for tree visualization
 * - TreeData - Backend support planned for tree visualization
 * - TableData - Merged into list visualization
 */

/**
 * Generic node for graph visualization.
 * 
 * @template T - Type of domain-specific data
 * 
 * @example
 * const node: Node<PersonData> = {
 *   id: "person_1",
 *   data: { name: "Alice", age: 30 },
 *   label: "Alice (age 30)"
 * };
 */
export interface Node<T> {
  /** Unique node identifier within the graph */
  id: string;
  /** Domain-specific data (type depends on use case) */
  data: T;
  /** Display label for UI rendering */
  label: string;
}

/**
 * Generic edge connecting two nodes.
 * 
 * @template T - Type of edge metadata
 * 
 * @example
 * const edge: Edge<RelationData> = {
 *   source: "person_1",
 *   target: "person_2",
 *   data: { relation: "friend", since: 2020 },
 *   label: "friend since 2020"
 * };
 */
export interface Edge<T> {
  /** Source node identifier */
  source: string;
  /** Target node identifier */
  target: string;
  /** Edge metadata */
  data: T;
  /** Display label for edge */
  label: string;
}

/**
 * Generic item for list/table visualization.
 * 
 * @template T - Type of item data
 * 
 * @example
 * const item: Item<PersonData> = {
 *   id: "person_1",
 *   data: { name: "Alice", age: 30 },
 *   label: "Alice"
 * };
 */
export interface Item<T> {
  /** Unique item identifier */
  id: string;
  /** Item data */
  data: T;
  /** Display label */
  label: string;
}

/**
 * Multi-node edge connecting more than 2 nodes.
 * Used for hypergraph visualization.
 * 
 * @template T - Type of hyperedge metadata
 * 
 * @example
 * const hyperedge: Hyperedge<ProjectData> = {
 *   nodes: ["researcher_1", "researcher_2", "researcher_3"],
 *   data: { project: "AI Safety" },
 *   label: "AI Safety collaboration"
 * };
 */
export interface Hyperedge<T> {
  /** List of node IDs in this hyperedge (minimum 2) */
  nodes: string[];
  /** Hyperedge metadata */
  data: T;
  /** Display label */
  label: string;
}

// ============================================================================
// Internal API Models
// ============================================================================

/**
 * JSON Schema representation for data types.
 * Generated by Pydantic's model_json_schema() method.
 */
export interface SchemaUnit {
  schema: Record<string, any>;
}

/**
 * Metadata response for /api/meta endpoint.
 * Contains JSON schemas for all visualization data types.
 * 
 * Frontend uses these schemas to dynamically render property panels.
 */
export interface Meta {
  /** JSON Schema for nodes */
  node_schema?: Record<string, any>;
  /** JSON Schema for edges */
  edge_schema?: Record<string, any>;
  /** JSON Schema for individual items (lists/tables) */
  item_schema?: Record<string, any>;
  /** JSON Schema for hyperedges */
  hyperedge_schema?: Record<string, any>;
}

/**
 * Search query request.
 */
export interface SearchRequest {
  /** Search query string */
  query: string;
  /** Optional context data passed to search callback */
  context?: Record<string, any>;
}

/**
 * Search results response.
 */
export interface SearchResponse {
  /** List of matching item IDs */
  results: string[];
}

/**
 * Chat query request.
 */
export interface ChatRequest {
  /** User question or message */
  query: string;
  /** Optional context (conversation history, selected items, etc.) */
  context?: Record<string, any>;
}

/**
 * Chat response.
 */
export interface ChatResponse {
  /** Response text from LLM or callback */
  response: string;
  /** Optional list of source item IDs */
  sources?: string[];
}

/**
 * Complete visualization data payload for /api/data endpoint.
 */
export interface VisualizationData {
    payload: GraphPayload | HypergraphPayload | ListPayload;
}

export interface GraphData {
    nodes: Node<any>[];
    edges: Edge<any>[];
}

export interface HypergraphData {
    nodes: Node<any>[];
    edges: Hyperedge<any>[];
}

export interface ListData {
    items: Item<any>[];
}

export interface GraphPayload {
    type: "graph";
    data: GraphData;
}

export interface HypergraphPayload {
    type: "hypergraph";
    data: HypergraphData;
}

export interface ListPayload {
    type: "list";
    data: ListData;
}
