"""Internal API response models for FastAPI endpoints.

These models define the JSON responses returned by the REST API.
They are distinct from the public models (Node, Edge, etc.) and serve
as contracts between frontend and backend.

Models:
    - SchemaUnit: JSON Schema representation
    - MetaResponse: Schema + metadata for visualization
    - SearchRequest: Search query input
    - SearchResponse: Search results (matching item IDs)
    - ChatRequest: Chat query input
    - ChatResponse: Chat response with optional sources
    - VisualizationData: Complete visualization payload

Example:
    >>> from ontosight.server.models.api import MetaResponse
    >>>
    >>> meta = MetaResponse(
    ...     node_schema={...},
    ...     edge_schema={...},
    ...     item_schema={...}
    ... )
"""

from typing import Any, Dict, List, Optional
from pydantic import BaseModel, ConfigDict, Field


class SchemaUnit(BaseModel):
    """JSON Schema representation for data types.

    Generated by Pydantic's model_json_schema() method.
    Contains type information, properties, required fields, etc.

    Attributes:
        schema_: Complete JSON Schema object (nested dict)
    """

    model_config = ConfigDict(populate_by_name=True)

    schema_: Dict[str, Any] = Field(..., alias="schema", description="JSON Schema object")


class MetaResponse(BaseModel):
    """Metadata response for /api/meta endpoint.

    Contains schemas for all visualization data types, allowing the frontend
    to dynamically render property panels based on the schema.

    Attributes:
        node_schema: JSON Schema for node properties
        edge_schema: JSON Schema for edge properties
        item_schema: JSON Schema for individual items (for lists/tables)
        hyperedge_schema: JSON Schema for hyperedge properties
    """

    node_schema: Optional[Dict[str, Any]] = Field(None, description="JSON Schema for nodes")
    edge_schema: Optional[Dict[str, Any]] = Field(None, description="JSON Schema for edges")
    item_schema: Optional[Dict[str, Any]] = Field(
        None, description="JSON Schema for individual items"
    )
    hyperedge_schema: Optional[Dict[str, Any]] = Field(
        None, description="JSON Schema for hyperedges"
    )


class SearchRequest(BaseModel):
    """Search query request model.

    Attributes:
        query: Search query string
        context: Optional context data passed to search callback
    """

    query: str = Field(..., description="Search query string", min_length=1)
    context: Optional[Dict[str, Any]] = Field(None, description="Optional context data")


class SearchResponse(BaseModel):
    """Search results response model.

    Attributes:
        results: List of matching item IDs
    """

    results: List[str] = Field(default_factory=list, description="List of matching item IDs")


class ChatRequest(BaseModel):
    """Chat query request model.

    Attributes:
        query: User question
        context: Optional context (conversation history, selected items)
    """

    query: str = Field(..., description="User question or message", min_length=1)
    context: Optional[Dict[str, Any]] = Field(
        None, description="Optional context (history, selections, etc.)"
    )


class ChatResponse(BaseModel):
    """Chat response model.

    Attributes:
        response: LLM response text
        sources: Optional list of source item IDs
    """

    response: str = Field(..., description="Response text")
    sources: Optional[List[str]] = Field(None, description="Optional list of source item IDs")


class VisualizationData(BaseModel):
    """Complete visualization data payload for /api/data endpoint.

    Contains all nodes, edges, or items needed for rendering.

    Attributes:
        nodes: List of node data
        edges: List of edge data
        items: List of items (for table/list views)
        hyperedges: List of hyperedges
    """

    nodes: Optional[List[Dict[str, Any]]] = Field(None, description="List of node objects")
    edges: Optional[List[Dict[str, Any]]] = Field(None, description="List of edge objects")
    items: Optional[List[Dict[str, Any]]] = Field(None, description="List of items for table view")
    hyperedges: Optional[List[Dict[str, Any]]] = Field(
        None, description="List of hyperedge objects"
    )


__all__ = [
    "SchemaUnit",
    "MetaResponse",
    "SearchRequest",
    "SearchResponse",
    "ChatRequest",
    "ChatResponse",
    "VisualizationData",
]
